"""Shared test environment.

Shared q-data inputs are resolved only through the q-data catalog, so a
catalog is now part of a working environment the same way a database URL is.
Tests that build an :class:`AppConfig` incidentally get a small, hash-correct
catalog here rather than each having to construct one.

``tests/test_config.py`` deliberately clears the environment to assert that a
missing catalog is a hard failure; this fixture does not weaken that, because
those tests set ``clear=True`` themselves.
"""
from __future__ import annotations

import hashlib
import json
import os
from datetime import UTC, datetime
from pathlib import Path

import pytest

from ibkr_trader import bootstrap

CATALOG_DATASETS = (
    "xsto.world.calendar",
    "xsto.world.universe",
    "xsto.world.instrument_identity",
)


def write_catalog(root: Path) -> Path:
    entries: dict[str, dict[str, str]] = {}
    for dataset_id in CATALOG_DATASETS:
        relative = f"markets/xsto/datasets/{dataset_id.replace('.', '_')}/current/data.parquet"
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        payload = dataset_id.encode()
        target.write_bytes(payload)
        entries[dataset_id] = {
            "relative_path": relative,
            "content_hash": hashlib.sha256(payload).hexdigest(),
        }
    catalog = root / "catalog.json"
    catalog.write_text(json.dumps({"contract_version": 1, "datasets": entries}), encoding="utf-8")
    return catalog


def write_shortability_snapshot(output_root: Path) -> Path:
    """Write an empty Stockholm shortable-list snapshot under this service's output root.

    Short-sale validation reads this file and rejects any symbol not on it.
    Without the file at all it raises "snapshot is missing", which
    short-circuits the validation tests before they reach the rejection path
    they are asserting.

    It goes under ``output_root``, not beside the identity dataset. Seeding it
    into a q-data dataset directory would have the test fixture perform the
    exact write the production code was just changed to stop doing, and would
    make a test asserting that directory stays clean fail against correct code.

    The list is deliberately empty rather than populated: "nothing is
    shortable" is the safe fixture and the state those tests need. It is not a
    stand-in for real shortability data -- runtime code still fails loudly when
    the real snapshot is absent.
    """
    snapshot = output_root / "shortability" / "shortability_latest.json"
    snapshot.parent.mkdir(parents=True, exist_ok=True)
    as_of = datetime.now(UTC).astimezone().date().isoformat()
    snapshot.write_text(
        json.dumps({"as_of_date": as_of, "snapshot_at": as_of, "entries": []}),
        encoding="utf-8",
    )
    return snapshot


@pytest.fixture(autouse=True, scope="session")
def q_data_catalog(tmp_path_factory: pytest.TempPathFactory) -> Path:
    catalog = write_catalog(tmp_path_factory.mktemp("q-data"))
    os.environ.setdefault("Q_DATA_CATALOG_PATH", str(catalog))
    output_root = tmp_path_factory.mktemp("ibkr-output")
    os.environ.setdefault("IBKR_TRADER_OUTPUT_ROOT", str(output_root))
    write_shortability_snapshot(output_root)
    return catalog


@pytest.fixture(autouse=True)
def isolated_bootstrap_env(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, request: pytest.FixtureRequest
) -> Path | None:
    """Keep the test suite away from the real /etc/ibkr-trader/bootstrap.env.

    ``AppConfig.from_env()`` resolves the protected bootstrap path. On the live
    host that file exists and holds production secrets, so without this the
    suite reads them into the test process - and fails outright on a host where
    /etc/ibkr-trader is not traversable by the test user. Release evidence is
    generated by running this suite, so it must not touch that file.

    The default *constant* is patched rather than the environment variable,
    because many tests use ``patch.dict(os.environ, ..., clear=True)``, which
    strips an environment-based override and would silently restore the real
    path inside exactly the tests that call ``AppConfig.from_env()``.
    """
    if request.node.get_closest_marker("real_bootstrap_default"):
        # Only for the test that asserts the shipped default location itself.
        # It must not read the file, just compare the constant.
        return None
    path = tmp_path / "absent-bootstrap.env"
    monkeypatch.setattr(bootstrap, "DEFAULT_BOOTSTRAP_ENV_PATH", path)
    # The runtime environment is loaded once per process; without clearing it,
    # one test's resolved environment would leak into every later test.
    bootstrap.reset_runtime_environment_cache()
    # The path override is honoured ahead of the patched constant, so an
    # exported value would bypass this isolation entirely.
    monkeypatch.delenv(bootstrap.BOOTSTRAP_ENV_PATH_VAR, raising=False)
    return path


def pytest_configure(config: pytest.Config) -> None:
    config.addinivalue_line(
        "markers",
        "real_bootstrap_default: opt out of bootstrap path isolation; only for "
        "asserting the shipped default location, never for reading the file.",
    )
