#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Capture the active X desktop for the IB Gateway user service.

Usage:
  write_ibgateway_session_env.sh [--display :11] [--xauthority /path/to/.Xauthority] [--output /path/to/session.env]

If --display is omitted, the current DISPLAY environment variable is used.
If --xauthority is omitted, XAUTHORITY is used, falling back to ~/.Xauthority.
EOF
}

display_value="${DISPLAY:-}"
xauthority_value="${XAUTHORITY:-}"
output_path="${HOME}/.config/ibgateway/session.env"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --display)
            shift
            [[ $# -gt 0 ]] || { usage >&2; exit 2; }
            display_value="$1"
            ;;
        --display=*)
            display_value="${1#*=}"
            ;;
        --xauthority)
            shift
            [[ $# -gt 0 ]] || { usage >&2; exit 2; }
            xauthority_value="$1"
            ;;
        --xauthority=*)
            xauthority_value="${1#*=}"
            ;;
        --output)
            shift
            [[ $# -gt 0 ]] || { usage >&2; exit 2; }
            output_path="$1"
            ;;
        --output=*)
            output_path="${1#*=}"
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
    shift
done

if [[ -z "${display_value}" ]]; then
    echo "No DISPLAY supplied and DISPLAY is not set." >&2
    exit 1
fi

if [[ -z "${xauthority_value}" ]]; then
    xauthority_value="${HOME}/.Xauthority"
fi

if [[ ! -f "${xauthority_value}" ]]; then
    echo "XAUTHORITY file not found: ${xauthority_value}" >&2
    exit 1
fi

mkdir -p "$(dirname "${output_path}")"
umask 077
cat >"${output_path}" <<EOF
# Generated by write_ibgateway_session_env.sh on $(date --iso-8601=seconds)
DISPLAY=${display_value}
XAUTHORITY=${xauthority_value}
EOF
chmod 600 "${output_path}"

echo "Wrote ${output_path} with DISPLAY=${display_value} and XAUTHORITY=${xauthority_value}"
